name: CI
on:
 push:
    branches: 
      - main
jobs:
  build_ios:
    runs-on: macos-latest
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: flutter clean
        run: flutter clean

      - name: Restore packages
        run: flutter pub get

      - name: Create Framework dir
        run: |
          echo '开始创建文件件'
          ios_out_path='/Users/runner/work/flutter_module/flutter_module/build/flutter-libs/frameworks'
          echo $ios_out_path
          rm -rf build
          flutter build ios-framework --no-profile --no-debug || exit -1 
          echo "\n5\. 输出文件到 $ios_out_path"
          rm -rf $ios_out_path
          mkdir $ios_out_path
          cp -r build/ios/framework/Release/App.xcframework $ios_out_path
          echo 'App.xcframework搬运完成'
          if [ -d ${ios_out_path} ]; then
                echo "编译成功......"${ios_out_path}
          else
                echo "编译失败......"${ios_out_path}
          fi
      
     


