
name: CI
on:
 push:
    branches: 
      - main
jobs:
  build_ios:
    runs-on: macos-latest
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release
      ios_out_path: /Users/runner/work/build/flutter-libs/frameworks

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Git pull tag
        env: 
          # Github 仓库
          GITHUB_REPO: github.com/yonghuifan21/FlutterModuleSDK.git
          GITHUB_USERNAME: yonghuifan21
          GITHUB_EMAIL: andy_yonghui@163.com
          GITHUB_TOKEN: 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
        run: |
          rm -rf $ios_out_path
          mkdir -p $ios_out_path
          cd $ios_out_path
          git init 
          git config user.name "$GITHUB_USERNAME"
          git config user.email "$GITHUB_EMAIL"
          git add .
          git checkout -b release
          scheme='https://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@'
          echo 'scheme'$scheme
          proj_path=$scheme$GITHUB_REPO
          echo '项目地址'$proj_path
          git remote add origin $proj_path
          echo '设置源路径之前'
          git remote -v
          git remote set-url origin $proj_path
          echo '设置源路径之后'
          git remote -v
          git commit -m '打包提交成功' || echo "No changes, nothing to commit!"
          echo '代码提交成功'
          git push -u origin release
          echo "代码推送成功"
          LatestTag=`git describe --tags `git rev-list --tags --grep prod --max-count=1`
          indexdot=`echo "$LatestTag" | awk -F ''$.'' '{printf "%d", length($0)-length($NF)}'`
          endStr=${string:$(indexdot+1)}
          echo "获取到的tag最后几位" ${endStr}
          endtagint = {{endStr}}+1
          echo "修改之后的tag ${endtagint}"
          getTag=${${LatestTag}/%${endStr}/${endtagint}}
          echo "新增的版本号...... ${getTag}"
          git tag ${getTag}
          git push origin ${getTag}